Added population results table functionality
projecttacoma/fqm-execution-demo pull request #23
Opened 2021-06-30 14:11 UTC by eperelli

2021-06-30 21:01 UTC, mgramigna requested changes
[MG1] The app crashes when you choose summary MeasureReports (assuming this is what @MegRiley noticed as well. The reason for this is that we try to do that split on `MeasureReport.subject.reference`, but summary MeasureReports don't have a `subject`.

I think there should be another backlog task for supporting a slightly different looking table in the case of summary measure reports, but at the very least, we should safeguard it so the app doesn't crash. Maybe for now, only do the `id` parsing and the rendering of the table if the reportType is not `summary`

[MG2] I think we should update the spacing/layout of where the group ID is displayed in relation to the table. It would probably make sense to have the group ID above the table entirely, and then render the table below the group ID:

```
Group-1
| here | is | my | table
```

[MG3] I think we should consider placing the table in a different part of the screen. It might be a little confusing to the user when the table is right next to the JSON viewer/download button. I was thinking of something like this:

![image](https://user-images.githubusercontent.com/16297930/124031012-ca8d3000-d9c4-11eb-835a-a22538cc551b.png)



For MG2-3, we can accomplish this using material UI's Grid system. Let me know if you have questions about it and we can walk through it .

[MG Others] - All inline comments made

2021-06-30 21:01 UTC, mgramigna commented on src/components/Results/PopulationResults.tsx
> +const fhirpath = require('fhirpath');
The "standard" import that you'll see in Typescript projects is `import ___ from '___'` instead of `const ___ = require('___')`. If you switch this to the preferred `import fhirpath from 'fhirpath'`, VS Code will yell at you (softly). It will say something along the lines of:

> Could not find a declaration file for module 'fhirpath'

This means that the Javascript implementation of fhirpath does not export its own type declaration files (files that end in `.d.ts`. These files allow other Typescript projects to use the library with all of the types included. Using `require` won't show you this error.

Using `require` is a decent alternative, but it behooves us to add our own `.d.ts` for fhirpath into the project. That way, we can have stricter typing for function calls. This will also be a sweet exercise in nitty gritty typescript development. An example of a custom `.d.ts` file can be seen in fqm-execution [here](https://github.com/projecttacoma/fqm-execution/blob/master/src/types/CQLExecution.d.ts). Basically we are just exporting what the cql-execution library exports.

**Actual actions**:

* Suggest adding a `src/types/fhirpath.d.ts` file that declares the fhirpath module. This will allow the Typescript compiler to know where to look for the types when you do `import fhirpath from 'fhirpath'` example contents below:
``` Typescript
// fhirpath.d.ts
declare module 'fhirpath' {
  export function evaluate(<nameForArg1OfEvaluate>: <typeofarg1>, <nameofarg2>, <typeofarg2>): <type of return value>
}
```

`any` is probably fine for the first arg and return value;

* Switch all `const fhirpath = require('fhirpath')` statements into `import`s
* Profit

2021-06-30 21:01 UTC, mgramigna commented on src/components/Helpers/PatientHelper.ts
> +export default function PatientHelper(bundle: R4.IBundle, patientID: string): R4.IPatient {
It might be good to not make this a `default` export in case we have more functions in here in the future which we probably will (a file can only have one default export). You can just do `export function ___`

This will change the corresponding `index.ts`, see comment on that file too

2021-06-30 21:01 UTC, mgramigna commented on src/components/Helpers/PatientHelper.ts
> +export default function PatientHelper(bundle: R4.IBundle, patientID: string): R4.IPatient {
Comment 2 (nitpick), can this function be camelCase, and maybe have it be a more descriptive name? like `findPatientInBundle` or something

2021-06-30 21:01 UTC, mgramigna commented on src/components/Helpers/index.ts
> +export { default as PatientHelper } from './PatientHelper';
Assuming you swap away from the default export, you can just do `export * from './PatientHelper'`

Then, when you import it, you'd need to do: `import {functionName} from './Helpers'`

2021-06-30 21:01 UTC, mgramigna commented on src/components/Results/PopulationResults.tsx
> +  results: any;
I know I hinted at this before, but this can actually be a stricter type than `any`

(you'll need to import { R4 } from the fhir-types library

```suggestion
  results: R4.IMeasureReport_Group;
```

2021-06-30 21:01 UTC, mgramigna commented on src/components/Results/Results.tsx
> +          fhirpath.evaluate(results, 'MeasureReport.group').map((group: any) => {
```suggestion
          fhirpath.evaluate(results, 'MeasureReport.group').map((group: R4.IMeasureReport_Group) => {
```

see above comment regarding stricter typing of this

2021-06-30 21:01 UTC, mgramigna commented on src/components/Helpers/PatientHelper.ts
> +  return e?.resource as R4.IPatient;
I think it might be a good idea to have this function return `null` if `e` ends up being undefined. This might cause you to have to shuffle around a few types, but shouldn't be a huge deal. Might just need to add a few `if`s here and there

2021-06-30 21:46 UTC, MegRiley commented
> [MG1] The app crashes when you choose summary MeasureReports (assuming this is what @MegRiley noticed as well. The reason for this is that we try to do that split on `MeasureReport.subject.reference`, but summary MeasureReports don't have a `subject`.


Yes this was the crash I was seeing, I just wasn't sure if I was passing the correct bundles in/or if it only worked for specific measures.

2021-07-01 17:40 UTC, eperelli commented on src/components/Helpers/PatientHelper.ts
> +export default function PatientHelper(bundle: R4.IBundle, patientID: string): R4.IPatient {
I changed PatientHelper (function name) to findPatientInBundle

2021-07-02 14:54 UTC, eperelli commented on src/components/Helpers/PatientHelper.ts
> +  return e?.resource as R4.IPatient;
I think I did this correctly. I just added an if else statement to check if e was undefined and if it is then it returns null. If it's not, then it returns what I had before. I also had to change the return type to R4.IPatient | null.

2021-07-06 18:55 UTC, mgramigna approved these changes
lovely

2021-07-06 18:57 UTC, MegRiley commented
Looks go to me

2021-07-06 18:57 UTC, merged