Added highlighting for reasonDetail
projecttacoma/fqm-execution-demo pull request #39
Opened 2021-08-26 14:20 UTC by sarahmcdougall

# Summary
When accessing the Accordion View results and hovering over the `GuidanceResponse reasonDetail`, the relevant property that the `reasonDetail` is referencing is highlighted in the JSON viewer.

## New Behavior
All previous behavior is the same, aside from the addition of the highlighted property in the JSON viewer when hovering over the Accordion view results.

## Code Changes
A function `getSearchString` was created in `src/components/Results/DetectedIssueResources.tsx` to obtain the string in the JSON viewer that we want to highlight. The function takes in a resource and a path, and it traverses through the path’s layers to find the final value that should be highlighted.

A function `highlightJSON` was created to separate the string we want to highlight from the rest of the resource JSON, and then apply `<mark>` tags to apply the yellow highlighting. If we cannot find a string to highlight (which is the case with EXM124’s `GuidanceResponse` for `ValueMissing`, the stringified JSON is shown in the viewer like before. 

These functions are used in `handlePopoverOpen()` to set the popover content with the highlighted JSON. 

## Testing Guidance
* Run the demo app with the EXM130 measure bundle and denominator patient bundle, and select “Gaps in Care” as the output type. Under the Accordion view, click on the first `GuidanceResponse`, which is for `DateOutofRange`. Hover over the `reasonDetail` and check that the `”end”` key and corresponding value are highlighted under `performedPeriod`. This should be the only highlighted content.
* Run the demo app with the EXM124 measure bundle and denominator patient bundle, and select “Gaps in Care” as the output type. Under the Accordion view, click on the first `GuidanceResponse`, which is for `ValueMissingValueMissing`. Hover over the `reasonDetail` and check that all the JSON output appears in the viewer and that none of it is highlighted (since we are missing values).
* To further check the functionality of the `getSearchString` and `highlightJSON` functions, you could change the `const path` in `handlePopoverOpen()` to a hard-coded value, such as `subject.reference`. Check with EXM130 to see that the highlighting has appropriately changed.

2021-08-26 17:40 UTC, natjoe4 commented
Code all looks great and functionality works as described :)

2021-08-26 17:40 UTC, natjoe4 approved these changes

2021-08-27 19:04 UTC, hossenlopp requested changes
Clever solution for this but could break.

2021-08-27 19:04 UTC, hossenlopp commented on src/components/Results/DetectedIssueResources.tsx
> +    const [beginning, end] = JSONString.split(searchString);
There should be a check to make sure that it found and split the string into two pieces. Additionally it should be handled if it found more than one of the `searchString`. It could happen if say the `end` of a time period occurs twice in the resource.

I'd suggest checking the result of split has a length of 2. If it doesn't then fallback to not doing the highlight.

2021-08-27 19:04 UTC, hossenlopp commented on src/components/Results/DetectedIssueResources.tsx
> +  const JSONString = JSON.stringify(resource, null, 2);
NIT: `JSONString` isn't camel case. Suggest `jsonString`.

2021-08-30 19:46 UTC, hossenlopp approved these changes
This looks good now. I tested with a modification of `test-denom-EXM130-bundle` with an extension adding a carbon copy of the performedPeriod. It properly did the failsafe of not attempting a proper highlight.

This should work for most situations. There may be some quirks but they should all fail safe and not highlight which is good.

2021-08-30 20:02 UTC, merged